### ISSUE TITLE
Question: when rounding, do you also want to round the ms too?

### ISSUE THREAD

**Issue by chilts** [atruskie/round-date#1]
I was just thinking of writing exactly the same module! :) So firstly, thanks for this.

I tried it out but was surprised that it didn't also round the ms to the nearest second. e.g.

``` js
var roundDate = require("round-date")

var ts = roundDate.floor(15, new Date());
console.log('ts: ' + ts.toISOString())
```

gives ...

```
=> ts: 2015-03-30T08:13:00.050Z
```

Is this something you'd be interested in changing. If you're happy to the nearest second that's ok too. :) Cheers.

**Comment by atruskie** [comment]
:smile: I never even expected anyone to take notice of this.

Well spotted. It should of wiped out the millisecond component. Will fix soon.

**Comment by chilts** [comment]
Thanks. That's awesome! :)
